name: Terraform Destroy

on:
  workflow_dispatch:   # manual trigger button in GitHub
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Check confirmation
        run: |
          if [[ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]]; then
            echo "You must type DESTROY to run this workflow"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Decide tfvars based on branch chosen when running workflow
      - name: Select tfvars file
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "TFVARS_FILE=prod-terraform.tfvars" >> $GITHUB_ENV
            echo "Destroying PROD infrastructure"
          else
            echo "TFVARS_FILE=stage-terraform.tfvars" >> $GITHUB_ENV
            echo "Destroying DEV infrastructure"
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=${TFVARS_FILE}
